FROM nginx
RUN apt-get update
RUN apt-get install software-properties-common -y
RUN apt-get install gnupg -y
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8C47BE8E75BCA694
RUN add-apt-repository ppa:certbot/certbot -y
#RUN apt-get update
RUN apt-get install certbot python-certbot-nginx -y
#ADD ./docker/nginx/scripts/configure.sh /configure.sh
#RUN ["chmod", "+x", "/configure.sh"]
#CMD /configure.sh